language: node_js
node_js:
  - "12"
  - "13"
  - "14"
  
services:
  - docker
  
# before_install:
#   - docker images
  
deploy:
  provider: script
  script: docker images
  on:
    branch: master

notifications:
  email: false
